version: 2.1
executors:
    docker-publisher:
        environment:
            IMAGE_NAME: masterminddesign/masterminddesign-api
        docker:
            - image: circleci/buildpack-deps:stretch
jobs:
    build:
        executor: docker-publisher
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Build env file
                  command: |
                      touch .env
                      echo "MONGO_URI=$MONGO_URI" >> .env
                      echo "MONGO_DB=$MONGO_DB" >> .env
            - run:
                  name: Build Docker image
                  command: |
                      docker build -t $IMAGE_NAME:latest .
            - run:
                  name: Archive Docker image
                  command: docker save -o image.tar $IMAGE_NAME
            - persist_to_workspace:
                  root: .
                  paths:
                      - ./image.tar
    publish-dev:
        executor: docker-publisher
        steps:
            - attach_workspace:
                  at: /tmp/workspace
            - setup_remote_docker
            - run:
                  name: Load archived Docker image
                  command: docker load -i /tmp/workspace/image.tar
            - run:
                  name: Publish Docker Image to Docker Hub
                  command: |
                      docker login -u "$USERNAME" -p "$TOKEN" docker.pkg.github.com
                      IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
                      docker tag $IMAGE_NAME:dev $IMAGE_NAME:$IMAGE_TAG
                      docker push $IMAGE_NAME:dev
                      docker push $IMAGE_NAME:$IMAGE_TAG
    publish-latest:
        executor: docker-publisher
        steps:
            - attach_workspace:
                  at: /tmp/workspace
            - setup_remote_docker
            - run:
                  name: Load archived Docker image
                  command: docker load -i /tmp/workspace/image.tar
            - run:
                  name: Publish Docker Image to Docker Hub
                  command: |
                      docker login -u "$USERNAME" -p "$TOKEN" docker.pkg.github.com
                      IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
                      docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
                      docker push $IMAGE_NAME:latest
                      docker push $IMAGE_NAME:$IMAGE_TAG
    publish-tag:
        executor: docker-publisher
        steps:
            - attach_workspace:
                  at: /tmp/workspace
            - setup_remote_docker
            - run:
                  name: Load archived Docker image
                  command: docker load -i /tmp/workspace/image.tar
            - run:
                  name: Publish Docker Image to Docker Hub
                  command: |
                      docker login -u "$USERNAME" -p "$TOKEN" docker.pkg.github.com
                      IMAGE_TAG=${CIRCLE_TAG/v/''}
                      docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
                      docker push $IMAGE_NAME:latest
                      docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
    version: 2
    build:
        jobs:
            - build:
                  filters:
                      branches:
                          only:
                              - master
                              - develop
            - publish-dev:
                  requires:
                      - build
                  filters:
                      branches:
                          only: develop
            - publish-latest:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
    build-tags:
        jobs:
            - build:
                  filters:
                      tags:
                          only: /^v.*/
                      branches:
                          ignore: /.*/
            - publish-tag:
                  requires:
                      - build
                  filters:
                      tags:
                          only: /^v.*/
                      branches:
                          ignore: /.*/
